steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/armour-assistant/neuroguardian-repo/neuroguardian-backend",
        "-f",
        "deployment/backend/Dockerfile",
        ".",
      ]

images:
  - us-central1-docker.pkg.dev/armour-assistant/neuroguardian-repo/neuroguardian-backend